from __future__ import annotations

import hashlib
from pathlib import Path
import time

from . import __version__
from .metrics import role_metric
from .models import ApplicantView

DATA_ADDON_NAME = "KeystoneLensCompanionData"
DATA_ADDON_RELATIVE_DIR = Path("Interface") / "AddOns" / DATA_ADDON_NAME
CACHE_RELATIVE_PATH = DATA_ADDON_RELATIVE_DIR / "Data.lua"
DATA_ADDON_TOC_RELATIVE_PATH = DATA_ADDON_RELATIVE_DIR / f"{DATA_ADDON_NAME}.toc"
MAX_TOOLTIP_AGE_SECONDS = 12 * 60 * 60
TOOLTIP_CACHE_VERSION = 3


def _retail_dir_from_screenshots(screenshots_path: str) -> Path | None:
    if not screenshots_path:
        return None
    shots = Path(screenshots_path).expanduser()
    retail = shots.parent
    if shots.name.casefold() != "screenshots" or retail.name.casefold() != "_retail_":
        return None
    return retail


def addon_cache_path(screenshots_path: str) -> Path | None:
    retail = _retail_dir_from_screenshots(screenshots_path)
    return retail / CACHE_RELATIVE_PATH if retail else None


def data_addon_toc_path(screenshots_path: str) -> Path | None:
    retail = _retail_dir_from_screenshots(screenshots_path)
    return retail / DATA_ADDON_TOC_RELATIVE_PATH if retail else None


def render_data_addon_toc() -> str:
    return (
        "## Interface: 120007, 120100\n"
        "## Title: KeystoneLens Companion Data\n"
        "## Notes: Warm-start Warcraft Logs cache; live Group Finder values come from KeystoneLens Companion.\n"
        "## Author: KeystoneLens\n"
        f"## Version: {__version__}\n"
        "## DefaultState: enabled\n"
        "## Group: KeystoneLensBridge\n"
        "## Category: Dungeons & Raids\n"
        "## X-Category: Data Export\n"
        "## X-KeystoneLens-Generated: true\n\n"
        "Data.lua\n"
    )


def _lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", " ").replace("\n", " ") + '"'


def render_tooltip_cache(rows: list[ApplicantView], now: float | None = None) -> str:
    generated = int(now if now is not None else time.time())
    entries: list[str] = []
    seen: set[str] = set()

    for view in rows:
        if not view.applicant.name or not view.snapshot_listing:
            continue
        if view.wcl_status in {"queued", "loading", "disabled", "error", "none"}:
            continue

        metric = role_metric(view)
        if metric is None:
            continue

        activity_id = int(view.snapshot_listing.activity_id or 0)
        spec_id = int(view.applicant.spec_id or 0)
        if activity_id <= 0 or spec_id <= 0:
            continue

        key = view.applicant.name
        if key in seen:
            continue
        seen.add(key)

        metric_name, percentile = metric
        fetched_at = int(
            view.wcl.fetched_at
            if view.wcl and view.wcl.fetched_at > 0
            else generated
        )

        fields = [
            f"activityID={activity_id}",
            f"specID={spec_id}",
            f"metric={_lua_string(metric_name)}",
            f"percentile={percentile:.2f}",
            f"fetchedAt={fetched_at}",
        ]
        entries.append(f"    [{_lua_string(key)}]={{" + ",".join(fields) + "},")

    body = "\n".join(entries)
    return (
        "-- Generated by KeystoneLens Companion. Public Warcraft Logs stats only.\n"
        "_G.KeystoneLensTooltipCache = nil\n"
        "_G.KeystoneLensTooltipCacheV2 = nil\n"
        "_G.KeystoneLensTooltipCacheV3 = {\n"
        f"  version = {TOOLTIP_CACHE_VERSION},\n"
        f"  generatedAt = {generated},\n"
        f"  maxAge = {MAX_TOOLTIP_AGE_SECONDS},\n"
        "  entries = {\n"
        f"{body}\n"
        "  },\n"
        "}\n"
    )


class TooltipCacheSync:
    """Write a warm-start WCL cache; live LFG values use the Companion overlay."""

    def __init__(self, screenshots_path: str):
        self.path = addon_cache_path(screenshots_path)
        self.toc_path = data_addon_toc_path(screenshots_path)
        self.last_hash = ""
        self.last_error = ""
        self.last_written_at = 0.0
        self.last_file_mtime_ns = 0

    def _ensure_data_addon(self) -> None:
        if not self.path or not self.toc_path:
            raise OSError("Could not derive WoW addon path from Screenshots folder")
        self.path.parent.mkdir(parents=True, exist_ok=True)
        expected_toc = render_data_addon_toc()
        current = ""
        try:
            current = self.toc_path.read_text(encoding="utf-8")
        except OSError:
            pass
        if current != expected_toc:
            tmp_toc = self.toc_path.with_suffix(".toc.tmp")
            tmp_toc.write_text(expected_toc, encoding="utf-8")
            tmp_toc.replace(self.toc_path)

    def write(self, rows: list[ApplicantView]) -> bool:
        if not self.path:
            self.last_error = "Could not derive WoW addon path from Screenshots folder"
            return False

        text = render_tooltip_cache(rows)
        semantic = "\n".join(
            line for line in text.splitlines()
            if "generatedAt =" not in line
        )
        semantic_hash = hashlib.sha256(semantic.encode("utf-8")).hexdigest()

        if semantic_hash == self.last_hash:
            try:
                data_unchanged = self.path.stat().st_mtime_ns == self.last_file_mtime_ns
            except OSError:
                data_unchanged = False
            if data_unchanged:
                try:
                    self._ensure_data_addon()
                    self.last_error = ""
                    return True
                except OSError as exc:
                    self.last_error = str(exc)
                    return False

        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self.path.with_suffix(".tmp")
            tmp.write_text(text, encoding="utf-8")
            tmp.replace(self.path)
            self._ensure_data_addon()
            self.last_hash = semantic_hash
            self.last_error = ""
            self.last_written_at = time.time()
            try:
                self.last_file_mtime_ns = self.path.stat().st_mtime_ns
            except OSError:
                self.last_file_mtime_ns = 0
            return True
        except OSError as exc:
            self.last_error = str(exc)
            return False
