from __future__ import annotations

import hashlib
from pathlib import Path
import threading
import time

from . import __version__
from .metrics import role_metric
from .models import ApplicantView
from .preload import PreloadStore, render_lua_dataset
from .registries import ACTIVE_SEASON_KEY, canonical_dungeon_name, season_for_dungeon

DATA_ADDON_NAME = "KeystoneLensCompanionData"
DATA_ADDON_RELATIVE_DIR = Path("Interface") / "AddOns" / DATA_ADDON_NAME
CACHE_RELATIVE_PATH = DATA_ADDON_RELATIVE_DIR / "Data.lua"
DATA_ADDON_TOC_RELATIVE_PATH = DATA_ADDON_RELATIVE_DIR / f"{DATA_ADDON_NAME}.toc"


def _retail_dir_from_screenshots(screenshots_path: str) -> Path | None:
    if not screenshots_path:
        return None
    shots = Path(screenshots_path).expanduser()
    retail = shots.parent
    if shots.name.casefold() != "screenshots" or retail.name.casefold() != "_retail_":
        return None
    return retail


def addon_cache_path(screenshots_path: str) -> Path | None:
    retail = _retail_dir_from_screenshots(screenshots_path)
    return retail / CACHE_RELATIVE_PATH if retail else None


def data_addon_toc_path(screenshots_path: str) -> Path | None:
    retail = _retail_dir_from_screenshots(screenshots_path)
    return retail / DATA_ADDON_TOC_RELATIVE_PATH if retail else None


def render_data_addon_toc() -> str:
    return (
        "## Interface: 120007, 120100\n"
        "## Title: KeystoneLens Companion Data\n"
        "## Notes: Preloaded Warcraft Logs Mythic+ tooltip database generated by KeystoneLens Companion.\n"
        "## Author: KeystoneLens\n"
        f"## Version: {__version__}\n"
        "## DefaultState: enabled\n"
        "## Group: KeystoneLensBridge\n"
        "## Category: Dungeons & Raids\n"
        "## X-Category: Data Export\n"
        "## X-KeystoneLens-Generated: true\n\n"
        "Data.lua\n"
    )


def _rows_to_records(rows: list[ApplicantView]) -> tuple[str | None, list[dict[str, object]]]:
    records: list[dict[str, object]] = []
    region: str | None = None
    for view in rows:
        if not view.applicant.name or not view.snapshot_listing:
            continue
        metric = role_metric(view)
        if metric is None:
            continue
        dungeon = canonical_dungeon_name(view.snapshot_listing.dungeon_name)
        season = season_for_dungeon(dungeon)
        if not dungeon or season is None or season.key != ACTIVE_SEASON_KEY:
            continue
        spec_id = int(view.applicant.spec_id or 0)
        if spec_id <= 0:
            continue
        metric_name, percentile = metric
        fetched_at = float(
            view.wcl.fetched_at
            if view.wcl and view.wcl.fetched_at > 0
            else time.time()
        )
        records.append({
            "full_name": view.applicant.name,
            "spec_id": spec_id,
            "dungeon": dungeon,
            "season": ACTIVE_SEASON_KEY,
            "metric": metric_name,
            "percentile": percentile,
            "fetched_at": fetched_at,
        })
        if view.region:
            region = str(view.region).upper()
    return region, records


class TooltipCacheSync:
    """Maintain a persistent preload database and atomically publish it to WoW.

    WoW reads Data.lua only while loading addons. Writes performed during an
    active WoW session prepare the next addon load; they are never presented as
    live IPC.
    """

    def __init__(self, screenshots_path: str):
        self.path = addon_cache_path(screenshots_path)
        self.toc_path = data_addon_toc_path(screenshots_path)
        self.store = PreloadStore()
        self._lock = threading.RLock()
        self.last_hash = ""
        self.last_error = ""
        self.last_written_at = 0.0
        self.last_file_mtime_ns = 0

    @property
    def region(self) -> str:
        return self.store.region

    @property
    def record_count(self) -> int:
        _region, rows = self.store.snapshot()
        return len(rows)

    def _ensure_data_addon(self) -> None:
        if not self.path or not self.toc_path:
            raise OSError("Could not derive WoW addon path from Screenshots folder")
        self.path.parent.mkdir(parents=True, exist_ok=True)
        expected_toc = render_data_addon_toc()
        current = ""
        try:
            current = self.toc_path.read_text(encoding="utf-8")
        except OSError:
            pass
        if current != expected_toc:
            tmp_toc = self.toc_path.with_suffix(".toc.tmp")
            tmp_toc.write_text(expected_toc, encoding="utf-8")
            tmp_toc.replace(self.toc_path)

    def merge_external(self, records: list[dict[str, object]], *, region: str | None = None) -> int:
        with self._lock:
            changed = self.store.merge(records, region=region)
            if changed and not self.store.save():
                self.last_error = self.store.last_error
                return 0
            return changed

    def publish(self) -> bool:
        if not self.path:
            self.last_error = "Could not derive WoW addon path from Screenshots folder"
            return False

        with self._lock:
            region, records = self.store.snapshot()
            text = render_lua_dataset(region, records)
            semantic = "\n".join(
                line for line in text.splitlines()
                if "generatedAt =" not in line
            )
            semantic_hash = hashlib.sha256(semantic.encode("utf-8")).hexdigest()

            if semantic_hash == self.last_hash:
                try:
                    data_unchanged = self.path.stat().st_mtime_ns == self.last_file_mtime_ns
                except OSError:
                    data_unchanged = False
                if data_unchanged:
                    try:
                        self._ensure_data_addon()
                        self.last_error = ""
                        return True
                    except OSError as exc:
                        self.last_error = str(exc)
                        return False

            try:
                self.path.parent.mkdir(parents=True, exist_ok=True)
                tmp = self.path.with_suffix(".tmp")
                tmp.write_text(text, encoding="utf-8")
                tmp.replace(self.path)
                self._ensure_data_addon()
                self.last_hash = semantic_hash
                self.last_error = ""
                self.last_written_at = time.time()
                try:
                    self.last_file_mtime_ns = self.path.stat().st_mtime_ns
                except OSError:
                    self.last_file_mtime_ns = 0
                return True
            except OSError as exc:
                self.last_error = str(exc)
                return False

    def write(self, rows: list[ApplicantView]) -> bool:
        region, records = _rows_to_records(rows)
        with self._lock:
            if self.store.merge(records, region=region):
                if not self.store.save():
                    self.last_error = self.store.last_error
                    return False
            return self.publish()
