from __future__ import annotations
import hashlib
import math
from pathlib import Path
import time

from . import __version__
from .models import ApplicantView

DATA_ADDON_NAME = "KeystoneLensCompanionData"
DATA_ADDON_RELATIVE_DIR = Path("Interface") / "AddOns" / DATA_ADDON_NAME
CACHE_RELATIVE_PATH = DATA_ADDON_RELATIVE_DIR / "Data.lua"
DATA_ADDON_TOC_RELATIVE_PATH = DATA_ADDON_RELATIVE_DIR / f"{DATA_ADDON_NAME}.toc"
MAX_TOOLTIP_AGE_SECONDS = 12 * 60 * 60
TOOLTIP_CACHE_VERSION = 2


def _retail_dir_from_screenshots(screenshots_path: str) -> Path | None:
    if not screenshots_path:
        return None
    shots = Path(screenshots_path).expanduser()
    retail = shots.parent
    if shots.name.casefold() != "screenshots" or retail.name.casefold() != "_retail_":
        return None
    return retail


def addon_cache_path(screenshots_path: str) -> Path | None:
    """Infer the generated companion-data file from `<WoW>/_retail_/Screenshots`."""
    retail = _retail_dir_from_screenshots(screenshots_path)
    return retail / CACHE_RELATIVE_PATH if retail else None


def data_addon_toc_path(screenshots_path: str) -> Path | None:
    retail = _retail_dir_from_screenshots(screenshots_path)
    return retail / DATA_ADDON_TOC_RELATIVE_PATH if retail else None


def render_data_addon_toc() -> str:
    return (
        "## Interface: 120007, 120100\n"
        "## Title: KeystoneLens Companion Data\n"
        "## Notes: Local cached KeystoneLens score/WCL data generated by the desktop companion.\n"
        "## Author: KeystoneLens\n"
        f"## Version: {__version__}\n"
        "## DefaultState: enabled\n"
        "## Group: KeystoneLensBridge\n"
        "## Category: Dungeons & Raids\n"
        "## Category-deDE: Dungeons & Schlachtzüge\n"
        "## Category-esES: Mazmorras y bandas\n"
        "## Category-esMX: Calabozos y bandas\n"
        "## Category-frFR: Donjons et raids\n"
        "## Category-itIT: Spedizioni e incursioni\n"
        "## Category-koKR: 던전 및 공격대\n"
        "## Category-ptBR: Masmorras e Raides\n"
        "## Category-ruRU: Подземелья и рейды\n"
        "## Category-zhCN: 地下城和团队副本\n"
        "## Category-zhTW: 地城與團隊\n"
        "## X-Category: Data Export\n"
        "## X-KeystoneLens-Generated: true\n\n"
        "Data.lua\n"
    )


def _lua_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\r", " ").replace("\n", " ") + '"'


def _safe_number(value: float | int | None, fallback: float = 0.0) -> float:
    try:
        v = float(value) if value is not None else fallback
    except (TypeError, ValueError):
        return fallback
    return v if math.isfinite(v) else fallback


def _safe_confidence(value: object) -> str:
    confidence = str(value or "").strip().lower()
    return confidence if confidence in {"high", "medium", "low"} else "low"


def render_tooltip_cache(rows: list[ApplicantView], now: float | None = None) -> str:
    generated = int(now if now is not None else time.time())
    entries: list[str] = []
    # Identity alone is not enough for a score: target key/dungeon and spec are
    # scoring inputs. Persist that context so the in-game hook can fail closed
    # when a still-fresh Data.lua belongs to another listing or specialization.
    seen: set[str] = set()
    for view in rows:
        if not view.score or not view.applicant.name or not view.snapshot_listing:
            continue
        if view.rio_status in {"queued", "loading"} or view.wcl_status in {"queued", "loading"}:
            continue

        activity_id = int(view.snapshot_listing.activity_id or 0)
        key_level = int(view.snapshot_listing.key_level or 0)
        spec_id = int(view.applicant.spec_id or 0)
        if activity_id <= 0 or key_level <= 0 or spec_id <= 0:
            continue

        # Keep the exact WoW full name as the cache key. Python Unicode
        # casefolding is not byte-equivalent to Lua 5.1 string.lower for every
        # locale/script; exact identity is shared by APS1 and the LFG tooltip.
        key = view.applicant.name
        if key in seen:
            continue
        seen.add(key)
        score = view.score
        bracket = score.wcl_bracket or (next(iter(view.wcl.metric_brackets.values()), None) if view.wcl else None)
        fetched_candidates = [
            view.wcl.fetched_at if view.wcl and view.wcl.fetched_at > 0 else 0,
            view.rio.fetched_at if view.rio and view.rio.fetched_at > 0 else 0,
        ]
        fetched_at = int(max(fetched_candidates) or generated)
        fields = [
            f"activityID={activity_id}",
            f"keyLevel={key_level}",
            f"specID={spec_id}",
            f"score={int(score.score)}",
            f"label={_lua_string(score.label)}",
            f"confidence={_lua_string(_safe_confidence(getattr(score, 'confidence', 'low')))}",
            f"fetchedAt={fetched_at}",
            f"rioComponent={_safe_number(score.rio_score):.2f}",
            f"rioWeight={_safe_number(score.rio_weight):.4f}",
            f"wclWeight={_safe_number(score.wcl_weight):.4f}",
        ]
        if score.wcl_score is not None:
            fields.append(f"wclComponent={_safe_number(score.wcl_score):.2f}")
            fields.append(f"wclPercentile={_safe_number(score.wcl_score):.2f}")
        if bracket:
            fields.extend([
                f"wclKey={int(bracket.key_level)}",
                f"wclRuns={int(bracket.run_count)}",
            ])
        entries.append(f"    [{_lua_string(key)}]={{" + ",".join(fields) + "},")
    body = "\n".join(entries)
    return (
        "-- Generated by KeystoneLens Companion. Public stats only; no credentials.\n"
        "-- Clear the legacy v1 global so an older Bridge fails closed after a rollback.\n"
        "_G.KeystoneLensTooltipCache = nil\n"
        "_G.KeystoneLensTooltipCacheV2 = {\n"
        f"  version = {TOOLTIP_CACHE_VERSION},\n"
        f"  generatedAt = {generated},\n"
        f"  maxAge = {MAX_TOOLTIP_AGE_SECONDS},\n"
        "  entries = {\n"
        f"{body}\n"
        "  },\n"
        "}\n"
    )


class TooltipCacheSync:
    """Write dynamic tooltip data into a separate unmanaged companion-data addon.

    Keeping generated data outside the CurseForge-managed KeystoneLensBridge
    folder prevents normal companion updates from marking the published addon
    itself as a locally modified working copy.
    """

    def __init__(self, screenshots_path: str):
        self.path = addon_cache_path(screenshots_path)
        self.toc_path = data_addon_toc_path(screenshots_path)
        self.last_hash = ""
        self.last_error = ""
        self.last_written_at = 0.0
        self.last_file_mtime_ns = 0

    def _ensure_data_addon(self) -> None:
        if not self.path or not self.toc_path:
            raise OSError("Could not derive WoW addon path from Screenshots folder")
        self.path.parent.mkdir(parents=True, exist_ok=True)
        expected_toc = render_data_addon_toc()
        current = ""
        try:
            current = self.toc_path.read_text(encoding="utf-8")
        except OSError:
            pass
        if current != expected_toc:
            tmp_toc = self.toc_path.with_suffix(".toc.tmp")
            tmp_toc.write_text(expected_toc, encoding="utf-8")
            tmp_toc.replace(self.toc_path)

    def write(self, rows: list[ApplicantView]) -> bool:
        if not self.path:
            self.last_error = "Could not derive WoW addon path from Screenshots folder"
            return False
        text = render_tooltip_cache(rows)
        # generatedAt changes on every render; exclude only that file-level stamp.
        # Per-entry fetchedAt and scoring context are meaningful freshness data
        # and must trigger a rewrite even when the numeric score stayed unchanged.
        semantic = "\n".join(line for line in text.splitlines() if "generatedAt =" not in line)
        semantic_hash = hashlib.sha256(semantic.encode("utf-8")).hexdigest()
        if semantic_hash == self.last_hash:
            try:
                data_unchanged = self.path.stat().st_mtime_ns == self.last_file_mtime_ns
            except OSError:
                data_unchanged = False
            if data_unchanged:
                try:
                    # A no-op is only successful when the complete generated
                    # addon remains loadable. Heal a missing/corrupt TOC even
                    # when Data.lua itself did not change.
                    self._ensure_data_addon()
                    self.last_error = ""
                    return True
                except OSError as exc:
                    self.last_error = str(exc)
                    return False
        try:
            # Publish Data.lua before exposing/updating the generated addon TOC.
            # On a first-write failure WoW must not see a TOC that references a
            # Data.lua file that was never committed.
            self.path.parent.mkdir(parents=True, exist_ok=True)
            tmp = self.path.with_suffix(".tmp")
            tmp.write_text(text, encoding="utf-8")
            tmp.replace(self.path)
            self._ensure_data_addon()
            self.last_hash = semantic_hash
            self.last_error = ""
            self.last_written_at = time.time()
            try:
                self.last_file_mtime_ns = self.path.stat().st_mtime_ns
            except OSError:
                self.last_file_mtime_ns = 0
            return True
        except OSError as exc:
            self.last_error = str(exc)
            return False
